#define R_GCONF         0
#define R_GSTAT         1
#define R_IFCNT         2
#define R_SLAVECONF     3
#define R_OTP_PROG      4
#define R_OTP_READ      5
#define R_IOIN          6
#define R_FACTORY_CONF  7
#define R_IHOLD_IRUN    0x10
#define R_TPOWER_DOWN   0x11
#define R_TSTEP         0x12
#define R_TPWMTHRS      0x13
#define R_VACTUAL       0x22
#define R_TCOOLTHRS     0x14
#define R_SGTHRS        0x40
#define R_SG_RESULT     0x41
#define R_COOLCONF      0x42
#define R_MSCNT         0x6A
#define R_MSCURACT      0x6B
#define R_CHOPCONF      0x6C
#define R_DRV_STATUS    0x6F
#define R_PWMCONF       0x70
#define R_PWM_SCALE     0x71
#define R_PWM_AUTO      0x72